

variables:
  SQSGENERATOR_BUILD_DIR: build


stages:
  - build
  - test


build-all:
  before_script:
    - echo "[BUILD] | Checking gtest"
    - dpkg -l libgtest-dev
    - echo "[BUILD] | Checking boost"
    - dpkg -l libboost-python-dev
    - dpkg -l libboost-numpy-dev
    - dpkg -l libboost-system-dev
    - echo "[BUILD] | Checking cmake"
    - dpkg -l cmake
    - echo "[BUILD] | Creating build directory"
    - mkdir ${SQSGENERATOR_BUILD_DIR}
    - echo "[BUILD] | Preparing cmake files"
    - cd ${SQSGENERATOR_BUILD_DIR}
    - cmake ..
    - cd ..
  stage: build
  tags:
    - core
    - build
  script:
    - cmake --build ${SQSGENERATOR_BUILD_DIR}


test-core-rank:
  stage: test
  tags:
    - test
  script:
    - ./build/test/sqsgenerator.core.test.rank