

variables:
  SQSGENERATOR_BUILD_DIR: build


stages:
  - build
  - test

before_script:
  - echo "[BUILD] | Checking gtest"
  - dpkg -l libgtest-dev
  - echo "[BUILD] | Checking boost"
  - dpkg -l libboost-python-dev
  - dpkg -l libboost-numpy-dev
  - dpkg -l libboost-system-dev
  - echo "[BUILD] | Checking cmake"
  - dpkg -l cmake
  - echo "[BUILD] | Creating build directory"
  - mkdir ${SQSGENERATOR_BUILD_DIR}
  - echo "[BUILD] | Preparing cmake files"
  - cmake ..


build-core:
  stage: build
  variables:
    TARGET_NAME: sqsgenerator.core
  tags:
    - core
    - build
  script:
    - echo "[BUILD] | [TARGET=${TARGET_NAME}]"
    - cmake --build . --target ${TARGET_NAME}

build-core-test-rank:
  stage: build
  variables:
    TARGET_NAME: sqsgenerator.core.test.rank
  tags:
    - core
    - build
  script:
    - echo "[BUILD] | [TARGET=${TARGET_NAME}]"
    - cmake --build . --target ${TARGET_NAME}

build-python-data:
  stage: build
  variables:
    TARGET_NAME: data
  tags:
    - python
    - build
  script:
    - echo "[BUILD] | [TARGET=${TARGET_NAME}]"
    - cmake --build . --target ${TARGET_NAME}