stages:
  - build
  - test

image: alpine

before_script:
  - apt install update
  - apt install gcc

variables:
  BUILD_DIR: build

build:
  stage: build
  script:
    - echo "building in ${BUILD_DIR}"

