

stages:
  - build
  - test


build-all:
  before_script:
    - bash $HOME/bin/sqs-build-create-envs.sh
  stage: build
  tags:
    - core
    - build
  script:
    - echo $(pwd)
    - cp examples/cs-cl.sqs.yaml sqs.yaml
    - bash $HOME/bin/sqs-build-wheel.sh
  artifacts:
    paths:
      - dist/