

variables:
  SQSGENERATOR_BUILD_DIR: build

stages:
  - build

before_script:
  - echo "[BUILD] | Installing boost"
  - echo "[BUILD] | Installing cmake"
  - echo "[BUILD] | Installing gmp"

build-core:
  stage: build
  tags:
    - core
    - build
  script:
    - echo "BUILD core"