

variables:
  SQSGENERATOR_BUILD_DIR: build


stages:
  - build

before_script:
  - echo "[BUILD] | Checking gtest"
  - dpkg -l libgtest-dev
  - echo "[BUILD] | Checking boost"
  - dpkg -l libboost-python-dev
  - dpkg -l libboost-python-dev
  - echo "[BUILD] | Checking cmake"
  - dpkg -l cmake
  - echo "[BUILD] | Checking gmp"
  - dpkg -l libgmp-dev
  - dpkg -l libgmp-dev
  - echo "[BUILD] | Creating build directory"
  - mkdir ${SQSGENERATOR_BUILD_DIR}
  - echo "[BUILD] | Preparing cmake files"
  - cd ${SQSGENERATOR_BUILD_DIR}
  - cmake ..


build-core:
  stage: build
  variables:
    TARGET_NAME: sqsgenerator.core
  tags:
    - core
    - build
  script:
    - echo "[BUILD] | [TARGET=${TARGET_NAME}]"
    - make ${TARGET_NAME}