

stages:
  - build
  - test
  - deploy


build-wheels:
  before_script:
    - bash $HOME/bin/sqs-build-create-envs.sh
  stage: build
  tags:
    - build
  script:
    - echo $(pwd)
    - cp examples/cs-cl.sqs.yaml sqs.yaml
    - bash $HOME/bin/sqs-build-wheel.sh
  artifacts:
    paths:
      - dist/*.whl

test-wheels:
  before_script:
    - bash $HOME/bin/sqs-build-create-envs.sh
  stage: test
  tags:
    - test
  script:
    - bash $HOME/bin/sqs-test-wheel.sh
  artifacts:
    when: always
    reports:
      junit: test/test-reports/TEST-*.xml

test-wheels-coverage:
  before_script:
    - bash $HOME/bin/sqs-build-create-envs.sh
  stage: test
  tags:
    - test
  script:
    - bash $HOME/bin/sqs-test-wheel-coverage.sh
  artifacts:
    when: always
    reports:
      cobertura: test/coverage.xml



depoly-wheels:
  stage: deploy
  tags:
    - deploy
  script:
    - bash $HOME/bin/sqs-deploy-wheel.sh
